### ISSUE TITLE
Скачивание аудиозаписей

### ISSUE THREAD

**Issue by olnaz** [Mikecoon/musicbar#1]
Скачивание аудиозаписи начинается только в том случае, если её сначала воспроизвести, а затем нажать на "скачать". В обратном случае ничего не происходит.

**Comment by Mikecoon** [comment]
Я думаю, дело в том, что сервис сейчас не работает. Как только он заработает, я проверю.

**Comment by olnaz** [comment]
Как я заметил, после входа в аккаунт, _window.ap._currentPlaylist = false_, что, видимо, в будущем при попытке скачать аудиозапись и вызывает ошибку: _a.indexOfAudio is not a function_ (AudioPlayer.js:2797).

После воспроизведения любого аудио подгружается плейлист и, собственно, теперь любой трек можно скачать (даже не из этого плейлиста). После очистки плейлиста загрузка аудио работает нормально. 

Если перезайти в аккаунт, загрузка опять не будет работать до первого воспроизведения.

**Comment by Mikecoon** [comment]
Да, в новом ВК аудиозаписи привязаны к плейлисту и не хранят в верстке URL песни.
Чтобы получить его, нужно вызывать метод AudioPlayer.prototype._ensureHasURL, который делает запрос к серверу и возвращает URL этой песни.

Собственно, перед скачиванием я тоже вызываю этот метод, и видимо, дело в том, что ВК не сделали проверку на существование плейлиста в данный момент:

![image](https://cloud.githubusercontent.com/assets/5504685/18594837/8ad276a0-7c4a-11e6-9102-af1c256734f8.png)

**Comment by olnaz** [comment]
А если самому попробовать пофиксить этот баг? Расширение ведь всё равно подменяет файл целиком, как я понимаю. 
Если немного подредактировать функцию **AudioPlayer.prototype.getCurrentPlaylist**, у меня всё чудесным образом работает.

```
AudioPlayer.prototype.getCurrentPlaylist = function() {
  return this._currentPlaylist || new AudioPlaylist()
}
```

Правда, не знаю, сломает ли это что-нибудь. Вроде, не должно.

**Comment by Mikecoon** [comment]
Думаю, что не должно. Во всяком случае, хуже точно не станет.

В следующем обновлении измененная функция будет работать.

**Comment by olnaz** [comment]
Отлично! Спасибо.
